### PR TITLE
Various OpenShift Route namespace bug fixes

### LINKED ISSUE #335: wrong members in Service Config when creating multiple routes
Tested k8s-bigip-ctlr with OpenShift, create pods, services and edge routes in two namespaces as below:
```
[root@host-8-241-26 ~]# oc get route --all-namespaces 
NAMESPACE      NAME                     HOST/PORT                                                          PATH      SERVICES                 PORT      TERMINATION   WILDCARD
bigiptest      edge-route               bigip-edge.example.com                                                       service-unsecure         27017     edge          None
f5test         secured-edge-route       test-edge.example.com                                                        service-unsecure         27017     edge          None
[root@host-8-241-26 ~]# 
[root@host-8-241-26 ~]# oc get svc --all-namespaces
NAMESPACE      NAME                     CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
bigiptest      service-unsecure         172.30.196.9     <none>        27017/TCP                 2h
f5test         service-unsecure         172.30.11.23     <none>        27017/TCP                 3h
```
Check the objects on BIG-IP and found one of the pools has no member. Enable debug on k8s-bigip-ctrl and found below logs: 
```
2017/09/20 06:54:00 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2017/09/20 06:54:00 [DEBUG] Finished syncing virtual servers {Namespace:install-test ServiceName:mongodb} (40.36µs)
2017/09/20 06:54:00 [DEBUG] Configured rule: {openshift_route_f5test_secured-edge-route test-edge.example.com 0 [0xc4202a2e00] [0xc4202a2e40]}
2017/09/20 06:54:00 [DEBUG] Found endpoints for backend {ServiceName:service-unsecure ServicePort:27017 Namespace:f5test}: [{10.129.0.15 8080 user-enabled}]
2017/09/20 06:54:00 [DEBUG] Configured rule: {openshift_route_f5test_secured-edge-route test-edge.example.com 0 [0xc4202a2f00] [0xc4202a2f40]}
2017/09/20 06:54:00 [DEBUG] Found endpoints for backend {ServiceName:service-unsecure ServicePort:27017 Namespace:f5test}: [{10.129.0.15 8080 user-enabled}]
2017/09/20 06:54:00 [DEBUG] Updated 0 of 2 virtual server configs, deleted 0
2017/09/20 06:54:00 [DEBUG] Finished syncing virtual servers {Namespace:f5test ServiceName:service-unsecure} (68.358µs)
2017/09/20 06:54:00 [DEBUG] Configured rule: {openshift_route_bigiptest_edge-route bigip-edge.example.com 0 [0xc4202a3040] [0xc4202a3080]}
2017/09/20 06:54:00 [DEBUG] Found endpoints for backend {ServiceName:service-unsecure ServicePort:27017 Namespace:bigiptest}: [{10.129.0.16 8080 user-enabled}]
2017/09/20 06:54:00 [DEBUG] Configured rule: {openshift_route_bigiptest_edge-route bigip-edge.example.com 0 [0xc4202a3140] [0xc4202a3180]}
2017/09/20 06:54:00 [DEBUG] Found endpoints for backend {ServiceName:service-unsecure ServicePort:27017 Namespace:bigiptest}: [{10.129.0.16 8080 user-enabled}]
2017/09/20 06:54:00 [DEBUG] Updated 0 of 2 virtual server configs, deleted 0
<......snip......>
2017/09/20 06:54:16 [DEBUG] [2017-09-20 06:54:16,101 __main__ DEBUG] config handler woken for reset
2017/09/20 06:54:16 [DEBUG] [2017-09-20 06:54:16,101 __main__ DEBUG] loaded configuration file successfully
2017/09/20 06:54:16 [DEBUG] [2017-09-20 06:54:16,101 __main__ DEBUG] Service Config: {"pools": [{"name": "openshift_default_docker-registry", "members": [{"session": "user-enabled", "port": 5000, "address": "10.129.0.4"}], "loadBalancingMode": "round-robin"}, {"name": "openshift_default_registry-console", "members": [{"session": "user-enabled", "port": 9090, "address": "10.129.0.6"}], "loadBalancingMode": "round-robin"}, {"name": "openshift_install-test_nodejs-mongodb-example", "members": [{"session": "user-enabled", "port": 8080, "address": "10.129.0.11"}], "loadBalancingMode": "round-robin"}, {"name": "openshift_f5test_service-unsecure", "members": [{"session": "user-enabled", "port": 8080, "address": "10.129.0.16"}], "loadBalancingMode": "round-robin"}, {"name": "openshift_bigiptest_service-unsecure", "members": null, "loadBalancingMode": "round-robin"}], "iRules": [{"apiAnonymous": "\n\twhen HTTP_REQUEST {\n       HTTP::redirect https://[getfield [HTTP::host] \":\" 1]:443[HTTP::uri]\n    }", "name": "http_redirect_irule"}, {"apiAnonymous": "\nwhen CLIENT_ACCEPTED {\n\tTCP::collect\n}\n\nwhen CLIENT_DATA {\n\t# Byte 0 is the content type.\n\t# Bytes 1-2 are the TLS version.\n\t# Bytes 3-4 are the TLS payload length.\n\t# Bytes 5-$tls_payload_len are the TLS payload.\n\tbinary scan [TCP::payload] cSS tls_content_type tls_version tls_payload_len\n\n\tswitch $tls_version {\n\t\t\"769\" -\n\t\t\"770\" -\n\t\t\"771\" {\n\t\t\t# Content type of 22 indicates the TLS payload contains a handshake.\n\t\t\tif { $tls_content_type == 22 } {\n\t\t\t\t# Byte 5 (the first byte of the handshake) indicates the handshake\n\t\t\t\t# record type, and a value of 1 signifies that the handshake record is\n\t\t\t\t# a ClientHello.\n\t\t\t\tbinary scan [TCP::payload] @5c tls_handshake_record_type\n\t\t\t\tif { $tls_handshake_record_type == 1 } {\n\t\t\t\t\t# Bytes 6-8 are the handshake length (which we ignore).\n\t\t\t\t\t# Bytes 9-10 are the TLS version (which we ignore).\n\t\t\t\t\t# Bytes 11-42 are random data (which we ignore).\n\n\t\t\t\t\t# Byte 43 is the session ID length.  Following this are three\n\t\t\t\t\t# variable-length fields which we shall skip over.\n\t\t\t\t\tset record_offset 43\n\n\t\t\t\t\t# Skip the session ID.\n\t\t\t\t\tbinary scan [TCP::payload] @${record_offset}c tls_session_id_len\n\t\t\t\t\tincr record_offset [expr {1 + $tls_session_id_len}]\n\n\t\t\t\t\t# Skip the cipher_suites field.\n\t\t\t\t\tbinary scan [TCP::payload] @${record_offset}S tls_cipher_suites_len\n\t\t\t\t\tincr record_offset [expr {2 + $tls_cipher_suites_len}]\n\n\t\t\t\t\t# Skip the compression_methods field.\n\t\t\t\t\tbinary scan [TCP::payload] @${record_offset}c tls_compression_methods_len\n\t\t\t\t\tincr record_offset [expr {1 + $tls_compression_methods_len}]\n\n\t\t\t\t\t# Get the number of extensions, and store the extensions.\n\t\t\t\t\tbinary scan [TCP::payload] @${record_offset}S tls_extensions_len\n\t\t\t\t\tincr record_offset 2\n\t\t\t\t\tbinary scan [TCP::payload] @${record_offset}a* tls_extensions\n\n\t\t\t\t\tfor { set extension_start 0 }\n\t\t\t\t\t\t\t{ $tls_extensions_len - $extension_start == abs($tls_extensions_len - $extension_start) }\n\t\t\t\t\t\t\t{ incr extension_start 4 } {\n\t\t\t\t\t\t# Bytes 0-1 of the extension are the extension type.\n\t\t\t\t\t\t# Bytes 2-3 of the extension are the extension length.\n\t\t\t\t\t\tbinary scan $tls_extensions @${extension_start}SS extension_type extension_len\n\n\t\t\t\t\t\t# Extension type 00 is the ServerName extension.\n\t\t\t\t\t\tif { $extension_type == \"00\" } {\n\t\t\t\t\t\t\t# Bytes 4-5 of the extension are the SNI length (we ignore this).\n\n\t\t\t\t\t\t\t# Byte 6 of the extension is the SNI type.\n\t\t\t\t\t\t\tset sni_type_offset [expr {$extension_start + 6}]\n\t\t\t\t\t\t\tbinary scan $tls_extensions @${sni_type_offset}S sni_type\n\n\t\t\t\t\t\t\t# Type 0 is host_name.\n\t\t\t\t\t\t\tif { $sni_type == \"0\" } {\n\t\t\t\t\t\t\t\t# Bytes 7-8 of the extension are the SNI data (host_name)\n\t\t\t\t\t\t\t\t# length.\n\t\t\t\t\t\t\t\tset sni_len_offset [expr {$extension_start + 7}]\n\t\t\t\t\t\t\t\tbinary scan $tls_extensions @${sni_len_offset}S sni_len\n\n\t\t\t\t\t\t\t\t# Bytes 9-$sni_len are the SNI data (host_name).\n\t\t\t\t\t\t\t\tset sni_start [expr {$extension_start + 9}]\n\t\t\t\t\t\t\t\tbinary scan $tls_extensions @${sni_start}A${sni_len} tls_servername\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\n\t\t\t\t\t\tincr extension_start $extension_len\n\t\t\t\t\t}\n\n\t\t\t\t\tif { [info exists tls_servername] } {\n\t\t\t\t\t\tset servername_lower [string tolower $tls_servername]\n\t\t\t\t\t\tSSL::disable serverside\n\t\t\t\t\t\tif { [class match $servername_lower equals ssl_passthrough_servername_dg] } {\n\t\t\t\t\t\t\tpool [class match -value $servername_lower equals ssl_passthrough_servername_dg]\n\t\t\t\t\t\t\tSSL::disable\n\t\t\t\t\t\t\tHTTP::disable\n\t\t\t\t\t\t}\n\t\t\t\t\t\telseif { [class match $servername_lower equals ssl_reencrypt_servername_dg] } {\n\t\t\t\t\t\t\tpool [class match -value $servername_lower equals ssl_reencrypt_servername_dg]\n\t\t\t\t\t\t\tSSL::enable serverside\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n\n\tTCP::release\n}\n", "name": "openshift_passthrough_irule"}], "l7Policies": [{"name": "openshift_insecure_routes", "rules": [{"conditions": [{"name": "0", "request": true, "equals": true, "host": true, "values": ["nodejs-mongodb-example-install-test.apps.0919-vur.qe.rhcloud.com"], "httpHost": true}], "name": "openshift_route_install-test_nodejs-mongodb-example", "actions": [{"forward": true, "request": true, "name": "0", "pool": "/openshift/openshift_install-test_nodejs-mongodb-example"}]}], "controls": ["forwarding"], "strategy": "/Common/first-match", "legacy": true, "requires": ["http"]}, {"name": "openshift_secure_routes", "rules": [{"conditions": [{"name": "0", "request": true, "equals": true, "host": true, "values": ["test-edge.example.com"], "httpHost": true}], "name": "openshift_route_f5test_secured-edge-route", "actions": [{"forward": true, "request": true, "name": "0", "pool": "/openshift/openshift_f5test_service-unsecure"}]}, {"conditions": [{"name": "0", "request": true, "equals": true, "host": true, "values": ["bigip-edge.example.com"], "httpHost": true}], "name": "openshift_route_bigiptest_edge-route", "actions": [{"forward": true, "request": true, "name": "0", "pool": "/openshift/openshift_bigiptest_service-unsecure"}]}], "controls": ["forwarding"], "strategy": "/Common/first-match", "legacy": true, "requires": ["http"]}], "virtualServers": [{"name": "ose-vserver", "destination": "/openshift/10.66.144.125:80", "enabled": true, "sourceAddressTranslation": {"type": "automap"}, "profiles": [{"partition": "Common", "name": "http", "context": "all"}], "policies": [{"partition": "openshift", "name": "openshift_insecure_routes"}], "ipProtocol": "tcp"}, {"name": "https-ose-vserver", "rules": ["/openshift/openshift_passthrough_irule"], "destination": "/openshift/10.66.144.125:443", "enabled": true, "sourceAddressTranslation": {"type": "automap"}, "profiles": [{"partition": "Common", "name": "http", "context": "all"}, {"partition": "openshift", "name": "default-route-clientssl", "context": "clientside"}, {"partition": "openshift", "name": "edge-route-https-cert", "context": "clientside"}, {"partition": "openshift", "name": "secured-edge-route-https-cert", "context": "clientside"}], "policies": [{"partition": "openshift", "name": "openshift_secure_routes"}], "ipProtocol": "tcp"}], "internalDataGroups": [{"records": [{"data": "openshift_default_docker-registry", "name": "docker-registry-default.apps.0919-vur.qe.rhcloud.com"}, {"data": "openshift_default_registry-console", "name": "registry-console-default.apps.0919-vur.qe.rhcloud.com"}], "name": "ssl_passthrough_servername_dg"}, {"records": [], "name": "ssl_reencrypt_servername_dg"}]}
2017/09/20 06:54:16 [DEBUG] [2017-09-20 06:54:16,101 f5_cccl.service.manager DEBUG] apply_config start
2017/09/20 06:54:16 [DEBUG] [2017-09-20 06:54:16,102 f5_cccl.service.validation DEBUG] Validating desired config against CCCL API schema.
2017/09/20 06:54:16 [DEBUG] [2017-09-20 06:54:16,102 f5_cccl.service.validation DEBUG] validate start
2017/09/20 06:54:16 [DEBUG] [2017-09-20 06:54:16,104 f5_cccl.service.validation DEBUG] validate took 0.00248 seconds.
```
At beginning of the log, it shows the endpoint "10.129.0.16" for openshift_route_bigiptest_edge-route and endpoint "10.129.0.15" for openshift_route_f5test_secured-edge-route, but in the line of Service Config it shows: 
`"name": "openshift_f5test_service-unsecure", "members": [{"session": "user-enabled", "port": 8080, "address": "10.129.0.16"}], "loadBalancingMode": "round-robin"}, {"name": "openshift_bigiptest_service-unsecure", "members": null, "loadBalancingMode": "round-robin"}`
obviously, the member "10.129.0.15" is missing and wrong member for openshift_f5test_service-unsecure.

### PR DESCRIPTION
**Pull request by sjberman**
Problem: When services or routes with the same names were created in different namespaces,
this created a myriad of problems.
  1. The client ssl certs would clobber each other due to the
     naming.
  2. Pool members would not be populated for a second service if the service name
     was the same as another.
  3. Internal data groups were not deleted

Solution:
  1. Change the name of client ssl certs to be namespace and route specific.
  2. Make more namespace adjustments to handle services with the same names.
  3. Remove internal data groups when the associated routes are deleted.
  4. Handle data groups for different namespaces.

Fixes #335, #336

### CODE REVIEW

File: pkg/appmanager/appManager.go [hunk 1]
```diff
@@ -1523,7 +1524,8 @@ func (appMgr *Manager) handleConfigForType(
 	found := false
 	plIdx := 0
 	for i, pl := range rsCfg.Pools {
-		if pl.ServiceName == sKey.ServiceName {
+		if pl.ServiceName == sKey.ServiceName &&
+			strings.Contains(pl.Name, sKey.Namespace) {
```
Comment (f5gary) [inline pkg/appmanager/appManager.go]: I'm concerned about using string.Contains() here, as we can have subtle bugs depending on how users name their namespaces and routes (for example a route name that contains a string that is also the name of a namespace). It would be more accurate to decompose the pool name based on how we format it to correctly identify the namespace embedded in the pool name.

File: pkg/appmanager/appManager.go [hunk 2]
```diff
@@ -1785,52 +1787,64 @@ func (appMgr *Manager) deleteUnusedRoutes(namespace, svc string) {
...
+						if i >= len(cfg.Pools)-1 {
+							cfg.Pools = cfg.Pools[:len(cfg.Pools)-1]
+						} else {
+							copy(cfg.Pools[i:], cfg.Pools[i+1:])
+							cfg.Pools[len(cfg.Pools)-1] = Pool{}
+							cfg.Pools = cfg.Pools[:len(cfg.Pools)-1]
+						}
+						// Delete profile
+						if routeName != "" {
+							client := fmt.Sprintf("%s/openshift_route_%s_%s-client-ssl",
```
Comment (f5gary) [inline pkg/appmanager/appManager.go]: We should probably have functions that correctly format this name as well as the one for server profiles. I'm concerned that if we ever need to change the name (again) that we will miss some and have hard to find bugs.

File: pkg/appmanager/appManager.go (hunk 1 above)
Comment (sjberman) [reply pkg/appmanager/appManager.go]: I have a semi-solution for this. The reason it's a little tougher is because Route pools are named differently than ConfigMap/Ingress pools. ConfigMap/Ingress pool names start with the namespace. Route pool names start with "openshift", followed by the namespace. To know which case I'm in, I can check if the pool name starts with "openshift", which I'll assume means we are dealing with a Route pool. The only caveat is if there is a ConfigMap/Ingress resource in a namespace called "openshift", it will fall into this condition, which we don't want.

Comment (f5gary) [reply pkg/appmanager/appManager.go]: I think that is better than using string.Contains(). We should address the naming of pools for ConfigMap/Ingress for consistency and to avoid this problem.

Comment (sjberman) [reply pkg/appmanager/appManager.go]: Maybe we can address this in your restructure. I think changing this now will cause a lot of issues.
